# Generated by Django 4.0.2 on 2022-03-01 22:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qs_title', models.TextField(max_length=100, unique=True)),
                ('qs_type', models.TextField(choices=[('General', 'General'), ('Definition', 'Definition'), ('Signs', 'Signs'), ('Mtb', 'Mtb')], max_length=100)),
                ('qs_answer', models.TextField()),
                ('qs_date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('qs_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
