# Generated by Django 4.0.2 on 2022-03-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qs_title',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qs_type',
            field=models.CharField(choices=[('General', 'General'), ('Definition', 'Definition'), ('Signs', 'Signs'), ('Mtb', 'Mtb')], max_length=1000),
        ),
    ]
