# Generated by Django 4.0.2 on 2022-03-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='file',
        ),
        migrations.AlterField(
            model_name='notes',
            name='link',
            field=models.URLField(),
        ),
    ]
