# Generated by Django 4.0.2 on 2022-03-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb', '0002_remove_notes_file_alter_notes_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='owner',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
    ]
