# Generated by Django 4.0.2 on 2022-03-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb', '0003_alter_notes_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
