# Generated by Django 4.0.2 on 2022-03-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb', '0005_alter_notes_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='owner',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
    ]
