# Generated by Django 4.0.2 on 2022-03-01 22:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('hs_id', models.TextField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hs_title', models.TextField(max_length=100, unique=True)),
                ('hs_type', models.TextField(choices=[('Class A', 'Class A'), ('Class B', 'Class B'), ('Class C', 'Class C')], max_length=100)),
                ('hs_image', models.ImageField(upload_to='highway_signs')),
                ('hs_date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('hs_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
